### ISSUE TITLE
Adapt bigger sample intervals for Temperature Reading on Sensor 2.

### ISSUE THREAD

**Issue by OCISLY-ds** [Zyzonix/MGFieldPy#9]
Increase the Temperature Reading sample rate for the second sensor from 5 Minutes to at least 10 to minimize EM-Field Noise generated by the current induced. After that compare EM-Field Readings with sensor one to identify possible enhancements.

**Comment by Zyzonix** [comment]
Changing the measurement interval can be handled by changing the value ```temperatureCollectionInterval``` in ```config.py```. The value will be read as seconds between each measurement.
